# Generated by Django 5.2 on 2025-04-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preapproved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
